name: shared_models
description: A shared Dart package for models used in the EduConnect apps.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
